(()=>{
'use strict';
const VERSION='1.0.0'; const STORE='speedfact-data-v1';
const defaultDb={jobs:[],clients:[],parcels:[],works:['Traitement phytosanitaire','Semis','Fertilisation','Déchaumage','Récolte','Autre travail'],settings:{vat:20},invoiceSeq:1};
let db=loadDb(), wizard={step:1,work:'',client:'',date:today(),ha:'',price:'',parcel:'',commune:'',crop:'',bbch:'',organic:false,conversion:false,rpg:'',location:'',start:'',end:'',obs:'',products:[]}, jobFilter='all', currentInvoice=null;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function today(){return new Date().toISOString().slice(0,10)} function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function loadDb(){try{return {...defaultDb,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return structuredClone(defaultDb)}} function saveDb(){localStorage.setItem(STORE,JSON.stringify(db));renderHome()}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('screen-'+name).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$('bottomNav').classList.toggle('hidden',name==='invoice');window.scrollTo(0,0)}
function iconFor(work){let n=norm(work);return n.includes('trait')?'🍂':n.includes('sem')?'🌱':n.includes('fert')?'🧴':n.includes('decha')?'⚒':n.includes('recol')||n.includes('moiss')?'🌾':'•••'}
function statusBadge(j){return j.billed?'<span class="badge">Facturé</span>':'<span class="badge open">À facturer</span>'}
function jobRow(j){return `<div class="job-row"><div class="job-glyph">${iconFor(j.work)}</div><div class="job-main"><b>${esc(j.work)}</b><span>${esc(j.crop||j.parcel||'')} ${j.ha?'- '+Number(j.ha).toLocaleString('fr-FR',{maximumFractionDigits:2})+' ha':''}</span><small>${formatDate(j.date)} · ${esc(j.client)}</small></div>${statusBadge(j)}</div>`}
function formatDate(s){if(!s)return'';let d=new Date(s+'T12:00:00');return d.toLocaleDateString('fr-FR')}
function renderHome(){let open=db.jobs.filter(j=>!j.billed),now=new Date(),month=db.jobs.filter(j=>{let d=new Date(j.date+'T12:00:00');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});$('statBillable').textContent=open.length;$('statMonth').textContent=month.length;$('recentJobs').innerHTML=[...db.jobs].sort((a,b)=>b.id-a.id).slice(0,4).map(jobRow).join('')||'<div class="job-row"><div class="job-main"><b>Aucun chantier</b><small>Ton prochain chantier apparaîtra ici.</small></div></div>'}
function startJob(){wizard={step:1,work:'',client:'',date:today(),ha:'',price:'',parcel:'',commune:'',crop:'',bbch:'',organic:false,conversion:false,rpg:'',location:'',start:'',end:'',obs:'',products:[]};show('job');renderWizard()}
function isPhyto(){return norm(wizard.work).includes('trait')||norm(wizard.work).includes('pulver')}
function maxStep(){return isPhyto()?4:2}
function renderProgress(){let max=maxStep(),parts=[];for(let i=1;i<=max;i++){parts.push(`<span class="dot ${i<=wizard.step?'on':''}"></span>`);if(i<max)parts.push(`<span class="line ${i<wizard.step?'on':''}"></span>`)}$('progress').innerHTML=parts.join('')}
function footer(nextLabel='SUIVANT',fn='SpeedFact.nextStep()'){return `<div class="wizard-footer"><button class="mic-btn" onclick="SpeedFact.voiceStep()">●</button><button class="cta" onclick="${fn}">${nextLabel}</button></div>`}
function inputField(label,id,value='',placeholder='',type='text'){return `<label>${label}</label><input id="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" oninput="SpeedFact.syncWizard('${id}',this.value)">`}
function renderWizard(){renderProgress();let html='';if(wizard.step===1){html=`<div class="wizard-card"><h3>1. Type de travail</h3><div class="hint">Quel type de travail réalisez-vous ?</div><div class="work-grid">${db.works.map(w=>`<button class="work-tile ${wizard.work===w?'selected':''}" onclick="SpeedFact.chooseWork('${esc(w)}')"><span class="emoji">${iconFor(w)}</span><span>${esc(w)}</span></button>`).join('')}</div></div><div class="wizard-card"><h3>2. Informations générales</h3>${inputField('Date du chantier','date',wizard.date,'','date')}<label>Société / exploitation</label><div class="autocomplete"><input id="client" value="${esc(wizard.client)}" placeholder="Tape le nom" oninput="SpeedFact.clientInput(this.value)"><div id="clientSug" class="suggestions hidden"></div></div><div class="field-row">${inputField('Surface (ha)','ha',wizard.ha,'0,00','number')}${inputField('Tarif HT/ha','price',wizard.price,'','number')}</div>${inputField('Parcelle','parcel',wizard.parcel,'Tape le nom')}${inputField('Commune','commune',wizard.commune,'')}</div>${footer()}`}
else if(wizard.step===2&&isPhyto()){html=`<div class="wizard-card"><h3>3. Informations traitement</h3>${inputField('Culture','crop',wizard.crop,'Blé tendre, colza…')}${inputField('Stade BBCH','bbch',wizard.bbch,'Ex. 31 - 1er nœud')}<label class="toggle-line">Agriculture biologique <input type="checkbox" ${wizard.organic?'checked':''} onchange="SpeedFact.syncBool('organic',this.checked)"></label><label class="toggle-line">Parcelle en conversion AB <input type="checkbox" ${wizard.conversion?'checked':''} onchange="SpeedFact.syncBool('conversion',this.checked)"></label></div><div class="wizard-card"><h3>4. Localisation / registre</h3>${inputField('Référence RPG (îlot / parcelle)','rpg',wizard.rpg,'')}${inputField('Code INSEE commune ou GPS','location',wizard.location,'')}<div class="field-row">${inputField('Heure début','start',wizard.start,'','time')}${inputField('Heure fin','end',wizard.end,'','time')}</div></div>${footer()}`}
else if(wizard.step===3&&isPhyto()){html=`<div class="wizard-card"><div class="catalog-box"><div class="shield">✓</div><div><b>Catalogue E‑Phy</b><small>Produits autorisés au 25/08/2026</small></div></div><h3>Rechercher un produit</h3><div class="autocomplete"><input id="prodSearch" placeholder="Nom commercial, substance…" oninput="SpeedFact.searchProducts(this.value)"><div id="productSug" class="suggestions hidden"></div></div><div id="mixEditor">${renderMix()}</div></div>${footer('SUIVANT')}`}
else {html=`<div class="wizard-card"><h3>Récapitulatif</h3><div class="summary-list"><div class="summary-line"><span>${iconFor(wizard.work)}</span><b>${esc(wizard.work)}</b></div><div class="summary-line"><span>▦</span><span>${esc(wizard.crop||'')}</span></div><div class="summary-line"><span>▣</span><span>${formatDate(wizard.date)}</span></div><div class="summary-line"><span>▤</span><span>${esc(wizard.client)}</span></div><div class="summary-line"><span>⌖</span><span>Parcelle : ${esc(wizard.parcel||'—')}</span></div><div class="summary-line"><span>◌</span><span>Surface : ${Number(wizard.ha||0).toLocaleString('fr-FR')} ha</span></div></div></div>${isPhyto()?`<div class="wizard-card"><h3>Mélange</h3>${wizard.products.map(p=>`<div class="mix-summary"><b>› ${esc(p.name)}</b><span>${esc(p.dose||'—')} ${esc(p.unit||'L/ha')}</span></div>`).join('')}</div>`:''}<div class="wizard-card">${inputField('Observations','obs',wizard.obs,'Facultatif')}</div>${footer('ENREGISTRER LE CHANTIER','SpeedFact.saveJob()')}`}
$('wizard').innerHTML=html}
function chooseWork(w){wizard.work=w;renderWizard()}
function syncWizard(k,v){wizard[k]=v}
function syncBool(k,v){wizard[k]=v}
function clientInput(v){wizard.client=v;let sug=db.clients.filter(c=>norm(c).includes(norm(v))).slice(0,8),box=$('clientSug');box.innerHTML=sug.map(c=>`<button onclick="SpeedFact.pickClient('${esc(c)}')">${esc(c)}</button>`).join('');box.classList.toggle('hidden',!v||!sug.length)}
function pickClient(c){wizard.client=c;$('client').value=c;$('clientSug').classList.add('hidden')}
function nextStep(){if(wizard.step===1&&(!wizard.work||!wizard.client||!Number(wizard.ha))){alert('Indique au minimum le travail, la société et les hectares.');return} if(wizard.step===3&&isPhyto()&&!wizard.products.length){alert('Ajoute au moins un produit au mélange.');return} wizard.step++; if(!isPhyto()&&wizard.step>2)wizard.step=2; renderWizard();window.scrollTo(0,0)}
function levenshtein(a,b){a=norm(a);b=norm(b);let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]!==b[j-1]));prev=cur}return prev[b.length]}
function scoreProduct(p,q){let nq=norm(q),fields=[p.name,p.aliases,p.substances].filter(Boolean).flatMap(x=>String(x).split('|')),best=99;for(let f of fields){let nf=norm(f);if(nf===nq)return 0;if(nf.startsWith(nq))best=Math.min(best,.2);if(nf.includes(nq))best=Math.min(best,.5);if(nq.length>=4){let pref=nf.slice(0,Math.max(nq.length,Math.min(nf.length,nq.length+3)));best=Math.min(best,1+levenshtein(nq,pref)/Math.max(1,nq.length))}}return best}
function searchProducts(q){let box=$('productSug');if(!q||q.trim().length<2){box.classList.add('hidden');return}let res=(window.SPEEDFACT_PRODUCTS||[]).map(p=>[p,scoreProduct(p,q)]).filter(x=>x[1]<1.7).sort((a,b)=>a[1]-b[1]).slice(0,12);box.innerHTML=res.map(([p])=>`<button onclick="SpeedFact.addProduct('${esc(p.amm)}')"><b>${esc(p.name)}</b><small>${esc(p.substances||p.functions||'')} · AMM ${esc(p.amm)}</small></button>`).join('')||'<button>Aucun résultat</button>';box.classList.remove('hidden')}
function addProduct(amm){let p=(window.SPEEDFACT_PRODUCTS||[]).find(x=>String(x.amm)===String(amm));if(!p)return;wizard.products.push({name:p.name,amm:p.amm,dose:'',unit:'L/ha',target:'',mode:'',catalog:p});$('productSug').classList.add('hidden');$('prodSearch').value='';$('mixEditor').innerHTML=renderMix()}
function renderMix(){return wizard.products.map((p,i)=>`<div class="mix-row"><div class="mix-head"><div><b>${esc(p.name)}</b><small>AMM ${esc(p.amm)}</small></div><button onclick="SpeedFact.removeProduct(${i})">Retirer</button></div><div class="field-row">${inputMix('Dose / ha',i,'dose',p.dose)}${selectMix(i,p.unit)}</div>${inputMix('Cible (si applicable)',i,'target',p.target)}${inputMix("Mode d'application (si applicable)",i,'mode',p.mode)}</div>`).join('')}
function inputMix(label,i,key,val){return `<div><label>${label}</label><input value="${esc(val)}" oninput="SpeedFact.mixChange(${i},'${key}',this.value)"></div>`}
function selectMix(i,val){return `<div><label>Unité</label><select onchange="SpeedFact.mixChange(${i},'unit',this.value)">${['L/ha','kg/ha','g/ha','mL/ha','unité/ha'].map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select></div>`}
function mixChange(i,k,v){wizard.products[i][k]=v} function removeProduct(i){wizard.products.splice(i,1);$('mixEditor').innerHTML=renderMix()}
function saveJob(){let j={id:Date.now(),...wizard,ha:Number(wizard.ha)||0,price:Number(wizard.price)||0,phyto:isPhyto(),billed:false,invoiceNo:null};delete j.step;if(!j.client||!j.work||!j.ha){alert('Société, travail et hectares sont obligatoires.');return}if(j.phyto&&!j.products.length){alert('Ajoute au moins un produit.');return}db.jobs.push(j);if(!db.clients.includes(j.client))db.clients.push(j.client);if(j.parcel&&!db.parcels.includes(j.parcel))db.parcels.push(j.parcel);saveDb();showJobs()}
function showJobs(){show('jobs');renderJobs()} function setJobFilter(f){jobFilter=f;document.querySelectorAll('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderJobs()} function toggleJobFilter(){$('jobFilterBox').classList.toggle('hidden');if(!$('jobFilterBox').classList.contains('hidden'))$('jobSearch').focus()}
function renderJobs(){let q=norm($('jobSearch')?.value||''),arr=[...db.jobs].sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(jobFilter==='open')arr=arr.filter(j=>!j.billed);if(jobFilter==='billed')arr=arr.filter(j=>j.billed);if(q)arr=arr.filter(j=>norm([j.client,j.work,j.parcel,j.crop].join(' ')).includes(q));let groups={};arr.forEach(j=>{let d=new Date(j.date+'T12:00:00'),k=d.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}).toUpperCase();(groups[k]??=[]).push(j)});$('jobsList').innerHTML=Object.entries(groups).map(([m,js])=>`<div class="month-title">${m}</div>${js.map(jobRow).join('')}`).join('')||'<div class="panel">Aucun chantier.</div>'}
function showBilling(){show('billing');renderBilling()}
function renderBilling(){let input=$('billingClient'),q=norm(input?.value||''),open=db.jobs.filter(j=>!j.billed),clients=[...new Set(open.map(j=>j.client))];if(input){let sug=clients.filter(c=>norm(c).includes(q)).slice(0,8),box=$('billingClientSug');box.innerHTML=sug.map(c=>`<button onclick="SpeedFact.pickBillingClient('${esc(c)}')">${esc(c)}</button>`).join('');box.classList.toggle('hidden',!q||!sug.length)}if(q)open=open.filter(j=>norm(j.client).includes(q));$('billingList').innerHTML=open.map(j=>`<label class="bill-card"><input type="checkbox" class="billcheck" value="${j.id}" checked><div><b>${esc(j.work)}</b><div>${Number(j.ha).toLocaleString('fr-FR')} ha · ${formatDate(j.date)}</div><small>${esc(j.client)} · ${esc(j.parcel||'')}</small></div><b>${(j.ha*j.price).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</b></label>`).join('')||'<div class="panel">Aucun travail non facturé.</div>'}
function pickBillingClient(c){$('billingClient').value=c;$('billingClientSug').classList.add('hidden');renderBilling()}
function createInvoice(){let ids=[...document.querySelectorAll('.billcheck:checked')].map(x=>Number(x.value)),jobs=db.jobs.filter(j=>ids.includes(j.id));if(!jobs.length){alert('Sélectionne au moins un chantier.');return}let client=jobs[0].client;if(jobs.some(j=>j.client!==client)){alert('Une facture ne peut contenir qu’une seule société. Filtre d’abord par client.');return}let vat=Number(db.settings.vat||20),num=`${new Date().getFullYear()}-${String(db.invoiceSeq).padStart(4,'0')}`,ht=jobs.reduce((s,j)=>s+j.ha*j.price,0);currentInvoice={ids,jobs,client,num,ht,vat};$('invoiceDocument').innerHTML=renderInvoice(currentInvoice);show('invoice')}
function renderInvoice(inv){let s=db.settings||{},vatAmount=inv.ht*inv.vat/100,ttc=inv.ht+vatAmount;return `<article class="invoice-page"><div class="invoice-head"><div><div class="invoice-title">FACTURE</div><div>${esc(s.issuer||'Speed Fact')}</div>${s.siret?`<small>SIRET ${esc(s.siret)}</small>`:''}${s.approval?`<small><br>Agrément phyto : ${esc(s.approval)}</small>`:''}</div><div><b>N° ${esc(inv.num)}</b><br>${new Date().toLocaleDateString('fr-FR')}</div></div><div class="invoice-parties"><div><b>Émetteur</b><p>${esc(s.issuerInfo||'')}</p></div><div><b>Client</b><p>${esc(inv.client)}</p></div></div><table class="invoice-table"><thead><tr><th>Prestation</th><th>Quantité</th><th>Prix HT</th><th>Total HT</th></tr></thead><tbody>${inv.jobs.map(j=>`<tr><td>${esc(j.work)}${j.parcel?`<br><small>${esc(j.parcel)}</small>`:''}</td><td>${j.ha.toLocaleString('fr-FR')} ha</td><td>${j.price.toLocaleString('fr-FR',{minimumFractionDigits:2})} €/ha</td><td>${(j.ha*j.price).toLocaleString('fr-FR',{minimumFractionDigits:2})} €</td></tr>`).join('')}</tbody></table><div class="invoice-total"><div>Total HT : ${inv.ht.toLocaleString('fr-FR',{minimumFractionDigits:2})} €</div><div>TVA ${inv.vat}% : ${vatAmount.toLocaleString('fr-FR',{minimumFractionDigits:2})} €</div><strong>Total TTC : ${ttc.toLocaleString('fr-FR',{minimumFractionDigits:2})} €</strong></div><p style="margin-top:45px;font-size:12px">Merci pour votre confiance.</p></article>${inv.jobs.map((j,i)=>renderAnnex(j,i+1)).join('')}`}
function renderAnnex(j,n){return `<article class="annex-page"><div class="annex-head"><div><b>SPEED FACT</b><br><small>Fiche chantier ${n}</small></div><div><b>FICHE CHANTIER</b><br><small>${j.phyto?'Traitement phytosanitaire':'Travaux agricoles'}</small></div></div><div class="annex-grid"><div><b>Exploitant / Client</b><br>${esc(j.client)}</div><div><b>Date</b><br>${formatDate(j.date)}</div><div><b>Parcelle</b><br>${esc(j.parcel||'—')}</div><div><b>Surface</b><br>${j.ha.toLocaleString('fr-FR')} ha</div><div><b>Travail</b><br>${esc(j.work)}</div><div><b>Commune</b><br>${esc(j.commune||'—')}</div>${j.phyto?`<div><b>Culture</b><br>${esc(j.crop||'—')}</div><div><b>Stade BBCH</b><br>${esc(j.bbch||'—')}</div><div><b>AB</b><br>${j.organic?'Oui':'Non'}</div><div><b>RPG / localisation</b><br>${esc(j.rpg||j.location||'—')}</div>`:''}</div>${j.phyto?`<h3>Produits utilisés</h3><table class="annex-prod"><thead><tr><th>Produit</th><th>AMM</th><th>Dose / ha</th><th>Cible</th></tr></thead><tbody>${j.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.amm)}</td><td>${esc(p.dose)} ${esc(p.unit)}</td><td>${esc(p.target||'')}</td></tr>`).join('')}</tbody></table>`:''}${j.obs?`<p><b>Observations :</b> ${esc(j.obs)}</p>`:''}</article>`}
function sendInvoice(){if(!currentInvoice)return;currentInvoice.ids.forEach(id=>{let j=db.jobs.find(x=>x.id===id);if(j){j.billed=true;j.invoiceNo=currentInvoice.num}});db.invoiceSeq++;saveDb();let subj=encodeURIComponent(`Facture ${currentInvoice.num} - ${currentInvoice.client}`),body=encodeURIComponent('Bonjour,\n\nVeuillez trouver la facture et les fiches chantier correspondantes en annexe.\n\nCordialement.');location.href=`mailto:?subject=${subj}&body=${body}`;alert('Les travaux sont marqués facturés. Génère le PDF puis joins-le au message.')}
function openSettings(){show('settings');let s=db.settings||{};$('issuer').value=s.issuer||'';$('siret').value=s.siret||'';$('approval').value=s.approval||'';$('issuerInfo').value=s.issuerInfo||'';$('vat').value=s.vat??20;$('catalogStatus').textContent=`${(window.SPEEDFACT_PRODUCTS||[]).length.toLocaleString('fr-FR')} produits autorisés chargés.`}
function saveSettings(){db.settings={issuer:$('issuer').value.trim(),siret:$('siret').value.trim(),approval:$('approval').value.trim(),issuerInfo:$('issuerInfo').value.trim(),vat:Number($('vat').value)||0};saveDb();alert('Réglages enregistrés.')}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download=`speed-fact-sauvegarde-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db={...defaultDb,...JSON.parse(r.result)};saveDb();alert('Sauvegarde restaurée.');openSettings()}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f)}
function voiceStep(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('La reconnaissance vocale n’est pas disponible dans ce navigateur. Tu peux tout saisir au clavier.');return}let r=new SR();r.lang='fr-FR';r.interimResults=false;r.onresult=e=>{let t=e.results[0][0].transcript;if(wizard.step===1){let m=t.match(/(\d+(?:[,.]\d+)?)\s*(?:ha|hectares?)/i);if(m)wizard.ha=m[1].replace(',','.');let w=db.works.find(x=>norm(t).includes(norm(x).slice(0,Math.min(6,norm(x).length))));if(w)wizard.work=w;let c=db.clients.find(x=>norm(t).includes(norm(x)));if(c)wizard.client=c;else if(!wizard.client)wizard.client=t} else if(wizard.step===2&&isPhyto()){wizard.crop=wizard.crop||t} else if(wizard.step===3&&isPhyto()){let q=t;let p=(window.SPEEDFACT_PRODUCTS||[]).map(x=>[x,scoreProduct(x,q)]).sort((a,b)=>a[1]-b[1])[0];if(p&&p[1]<1.7){wizard.products.push({name:p[0].name,amm:p[0].amm,dose:'',unit:'L/ha',target:'',mode:'',catalog:p[0]})}} else wizard.obs=t;renderWizard()};r.start()}
function goHome(){show('home');renderHome()} function showBillingNav(){showBilling()} function showJobsNav(){showJobs()}
async function checkUpdate(manual=false){try{let r=await fetch(`version.json?ts=${Date.now()}`,{cache:'no-store'}),v=await r.json();$('updateStatus')&&($('updateStatus').textContent=`Version installée : ${VERSION} · version web : ${v.version}`);if(v.version!==VERSION){$('updateBanner').classList.remove('hidden')}else if(manual)alert('Speed Fact est à jour.')}catch(e){if(manual)alert('Impossible de vérifier la mise à jour pour le moment.') }}
async function applyUpdate(){if('serviceWorker'in navigator){let reg=await navigator.serviceWorker.getRegistration();if(reg){await reg.update();if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});else if(reg.installing)reg.installing.addEventListener('statechange',()=>{if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'})})}}setTimeout(()=>location.reload(),800)}
function registerSW(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{reg.update();reg.addEventListener('updatefound',()=>{let w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)$('updateBanner').classList.remove('hidden')})})}).catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}
window.SpeedFact={startJob,goHome,showJobs,showBilling,openSettings,chooseWork,syncWizard,syncBool,clientInput,pickClient,nextStep,searchProducts,addProduct,removeProduct,mixChange,saveJob,setJobFilter,toggleJobFilter,renderJobs,renderBilling,pickBillingClient,createInvoice,sendInvoice,saveSettings,exportData,importData,voiceStep,checkUpdate,applyUpdate};
renderHome();show('home');registerSW();checkUpdate(false);
})();
