(()=>{
'use strict';
const VERSION='1.1.0', STORE='speedfact-data-v1';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const deep=x=>JSON.parse(JSON.stringify(x));
const defaultIssuer=()=>({id:Date.now(),name:'MEA',legalName:'',address:'',zip:'',city:'',siret:'',vatNo:'',phone:'',email:'',iban:'',bic:'',bank:'',paymentTerms:'30 jours fin de mois',approval:'',default:true});
const defaultDb={jobs:[],clients:[],parcels:[],works:['Traitement phytosanitaire','Semis','Fertilisation','Déchaumage','Récolte','Autre travail'],settings:{vat:20,defaultIssuerId:null},issuers:[],invoices:[],invoiceSeq:1};
let db=migrate(loadRaw()), wizard=newWizard(), jobFilter='all', currentInvoice=null, editingIssuerId=null, editingClientId=null, invoiceOrigin='billing';
function today(){return new Date().toISOString().slice(0,10)}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function formatDate(s){if(!s)return'';return new Date(s+'T12:00:00').toLocaleDateString('fr-FR')}
function eur(v){return Number(v||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}
function uid(){return Date.now()+Math.floor(Math.random()*10000)}
function loadRaw(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function migrate(raw){let d={...deep(defaultDb),...raw};d.settings={...defaultDb.settings,...(raw.settings||{})};
  if(!Array.isArray(d.jobs))d.jobs=[];if(!Array.isArray(d.invoices))d.invoices=[];if(!Array.isArray(d.issuers))d.issuers=[];
  if(!Array.isArray(d.clients))d.clients=[];
  d.clients=d.clients.map(c=>typeof c==='string'?{id:uid(),name:c,legalName:'',address:'',zip:'',city:'',siret:'',vatNo:'',phone:'',email:'',emails:[],exploitations:[]}:normalizeClient(c));
  if(!d.issuers.length){let old=raw.settings||{},i=defaultIssuer();i.name=old.issuer||'MEA';i.legalName=old.issuer||'';i.siret=old.siret||'';i.approval=old.approval||'';i.address=old.issuerInfo||'';d.issuers=[i];d.settings.defaultIssuerId=i.id}
  if(!d.settings.defaultIssuerId||!d.issuers.some(i=>String(i.id)===String(d.settings.defaultIssuerId))){d.settings.defaultIssuerId=d.issuers[0]?.id||null}
  d.issuers.forEach(i=>i.default=String(i.id)===String(d.settings.defaultIssuerId));
  d.jobs=d.jobs.map(j=>({...j,id:j.id||uid(),clientId:j.clientId||clientByNameIn(d,j.client)?.id||null,exploitation:j.exploitation||'',vat:Number(j.vat??d.settings.vat??20),billed:!!j.billed}));
  if(!d.invoiceSeq)d.invoiceSeq=1;return d}
function normalizeClient(c){return {id:c.id||uid(),name:c.name||c.legalName||'',legalName:c.legalName||'',address:c.address||'',zip:c.zip||'',city:c.city||'',siret:c.siret||'',vatNo:c.vatNo||'',phone:c.phone||'',email:c.email||'',emails:Array.isArray(c.emails)?c.emails:[],exploitations:Array.isArray(c.exploitations)?c.exploitations.map(e=>typeof e==='string'?{id:uid(),name:e,commune:'',parcels:[]}:{id:e.id||uid(),name:e.name||'',commune:e.commune||'',parcels:Array.isArray(e.parcels)?e.parcels:[]}):[]}}
function saveDb(){localStorage.setItem(STORE,JSON.stringify(db));renderHome()}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));let s=$('screen-'+name);if(s)s.classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$('bottomNav').classList.toggle('hidden',['invoice','issuers','clients','history','job'].includes(name));window.scrollTo(0,0)}
function currentIssuer(){return db.issuers.find(i=>String(i.id)===String(db.settings.defaultIssuerId))||db.issuers[0]||defaultIssuer()}
function clientByNameIn(d,name){return (d.clients||[]).find(c=>norm(typeof c==='string'?c:c.name)===norm(name||''))}
function clientByName(name){return db.clients.find(c=>norm(c.name)===norm(name||''))}
function clientById(id){return db.clients.find(c=>String(c.id)===String(id))}
function newWizard(){return {editingId:null,step:1,work:'',client:'',clientId:null,exploitation:'',date:today(),ha:'',price:'',vat:Number(db?.settings?.vat||20),parcel:'',commune:'',crop:'',bbch:'',organic:false,conversion:false,rpg:'',location:'',start:'',end:'',obs:'',products:[]}}
function iconFor(work){let n=norm(work);return n.includes('trait')?'🍂':n.includes('sem')?'🌱':n.includes('fert')?'🧴':n.includes('decha')?'⚒':n.includes('recol')||n.includes('moiss')?'🌾':'•••'}
function statusBadge(j){return j.billed?'<span class="badge">Facturé</span>':'<span class="badge open">À facturer</span>'}
function jobRow(j,actions=false){return `<div class="job-row"><div class="job-glyph">${iconFor(j.work)}</div><div class="job-main"><b>${esc(j.work)}</b><span>${esc(j.exploitation||j.crop||j.parcel||'')} ${j.ha?'- '+Number(j.ha).toLocaleString('fr-FR',{maximumFractionDigits:2})+' ha':''}</span><small>${formatDate(j.date)} · ${esc(j.client)}${j.parcel?' · '+esc(j.parcel):''}</small></div>${actions?`<div class="row-actions"><button onclick="SpeedFact.editJob(${j.id})">✎</button><button class="danger" onclick="SpeedFact.deleteJob(${j.id})">×</button></div>`:statusBadge(j)}</div>`}
function renderHome(){let open=db.jobs.filter(j=>!j.billed),now=new Date(),month=db.jobs.filter(j=>{let d=new Date(j.date+'T12:00:00');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});if($('statBillable'))$('statBillable').textContent=open.length;if($('statMonth'))$('statMonth').textContent=month.length;if($('recentJobs'))$('recentJobs').innerHTML=[...db.jobs].sort((a,b)=>b.id-a.id).slice(0,4).map(j=>jobRow(j)).join('')||'<div class="job-row"><div class="job-main"><b>Aucun chantier</b><small>Ton prochain chantier apparaîtra ici.</small></div></div>'}
function startJob(){wizard=newWizard();$('jobScreenTitle').textContent='Nouveau chantier';show('job');renderWizard()}
function editJob(id){let j=db.jobs.find(x=>x.id===id);if(!j)return;wizard={...newWizard(),...deep(j),editingId:id,step:1};$('jobScreenTitle').textContent='Modifier chantier';show('job');renderWizard()}
function deleteJob(id){let j=db.jobs.find(x=>x.id===id);if(!j||j.billed){alert(j?.billed?'Un chantier déjà facturé ne peut pas être supprimé ici.':'Chantier introuvable.');return}if(confirm('Supprimer définitivement ce chantier ?')){db.jobs=db.jobs.filter(x=>x.id!==id);saveDb();renderJobs()}}
function isPhyto(){return norm(wizard.work).includes('trait')||norm(wizard.work).includes('pulver')}
function maxStep(){return isPhyto()?4:2}
function renderProgress(){let max=maxStep(),parts=[];for(let i=1;i<=max;i++){parts.push(`<span class="dot ${i<=wizard.step?'on':''}"></span>`);if(i<max)parts.push(`<span class="line ${i<wizard.step?'on':''}"></span>`)}$('progress').innerHTML=parts.join('')}
function footer(nextLabel='SUIVANT',fn='SpeedFact.nextStep()'){return `<div class="wizard-footer"><button class="mic-btn" onclick="SpeedFact.voiceStep()">●</button><button class="cta" onclick="${fn}">${nextLabel}</button></div>`}
function inputField(label,id,value='',placeholder='',type='text',step=''){return `<label>${label}</label><input id="${id}" type="${type}" ${step?`step="${step}"`:''} value="${esc(value)}" placeholder="${esc(placeholder)}" oninput="SpeedFact.syncWizard('${id}',this.value)">`}
function clientSuggestions(v){let q=norm(v);return db.clients.filter(c=>!q||norm([c.name,c.legalName,c.city].join(' ')).includes(q)).slice(0,8)}
function exploitationOptions(){let c=clientById(wizard.clientId)||clientByName(wizard.client);let ex=c?.exploitations||[];return ex.map(e=>`<option value="${esc(e.name)}" ${e.name===wizard.exploitation?'selected':''}>${esc(e.name)}</option>`).join('')}
function renderWizard(){renderProgress();let html='';
  if(wizard.step===1){html=`<div class="wizard-card"><h3>1. Type de travail</h3><div class="hint">Quel type de travail réalisez-vous ?</div><div class="work-grid">${db.works.map(w=>`<button class="work-tile ${wizard.work===w?'selected':''}" onclick="SpeedFact.chooseWork('${esc(w)}')"><span class="emoji">${iconFor(w)}</span><span>${esc(w)}</span></button>`).join('')}</div></div><div class="wizard-card"><h3>2. Informations générales</h3>${inputField('Date du chantier','date',wizard.date,'','date')}<label>Client facturé</label><div class="autocomplete"><input id="client" value="${esc(wizard.client)}" placeholder="Tape le nom" oninput="SpeedFact.clientInput(this.value)"><div id="clientSug" class="suggestions hidden"></div></div><label>Exploitation</label><select id="exploitation" onchange="SpeedFact.syncWizard('exploitation',this.value)"><option value="">—</option>${exploitationOptions()}</select><div class="field-row">${inputField('Surface (ha)','ha',wizard.ha,'0,00','number','0.01')}${inputField('Tarif HT/ha','price',wizard.price,'','number','0.01')}</div><div class="field-row">${inputField('TVA (%)','vat',wizard.vat,'20','number','0.1')}${inputField('Commune','commune',wizard.commune,'')}</div>${inputField('Parcelle','parcel',wizard.parcel,'Tape le nom')}</div>${footer()}`}
  else if(wizard.step===2&&isPhyto()){html=`<div class="wizard-card"><h3>3. Informations traitement</h3>${inputField('Culture','crop',wizard.crop,'Blé tendre, colza…')}${inputField('Stade BBCH','bbch',wizard.bbch,'Ex. 31 - 1er nœud')}<label class="toggle-line">Agriculture biologique <input type="checkbox" ${wizard.organic?'checked':''} onchange="SpeedFact.syncBool('organic',this.checked)"></label><label class="toggle-line">Parcelle en conversion AB <input type="checkbox" ${wizard.conversion?'checked':''} onchange="SpeedFact.syncBool('conversion',this.checked)"></label></div><div class="wizard-card"><h3>4. Localisation / registre</h3>${inputField('Référence RPG (îlot / parcelle)','rpg',wizard.rpg,'')}${inputField('Code INSEE commune ou GPS','location',wizard.location,'')}<div class="field-row">${inputField('Heure début','start',wizard.start,'','time')}${inputField('Heure fin','end',wizard.end,'','time')}</div></div>${footer()}`}
  else if(wizard.step===3&&isPhyto()){html=`<div class="wizard-card"><div class="catalog-box"><div class="shield">✓</div><div><b>Catalogue E‑Phy</b><small>Produits autorisés au 25/08/2026</small></div></div><h3>Rechercher un produit</h3><div class="autocomplete"><input id="prodSearch" placeholder="Nom commercial, substance…" oninput="SpeedFact.searchProducts(this.value)"><div id="productSug" class="suggestions hidden"></div></div><div id="mixEditor">${renderMix()}</div></div>${footer('SUIVANT')}`}
  else {html=`<div class="wizard-card"><h3>Récapitulatif</h3><div class="summary-list"><div class="summary-line"><span>${iconFor(wizard.work)}</span><b>${esc(wizard.work)}</b></div><div class="summary-line"><span>▣</span><span>${formatDate(wizard.date)}</span></div><div class="summary-line"><span>▤</span><span>${esc(wizard.client)}${wizard.exploitation?' · '+esc(wizard.exploitation):''}</span></div><div class="summary-line"><span>⌖</span><span>Parcelle : ${esc(wizard.parcel||'—')}</span></div><div class="summary-line"><span>◌</span><span>${Number(wizard.ha||0).toLocaleString('fr-FR')} ha · ${eur(Number(wizard.price||0))}/ha · TVA ${Number(wizard.vat||0).toLocaleString('fr-FR')} %</span></div></div></div>${isPhyto()?`<div class="wizard-card"><h3>Mélange</h3>${wizard.products.map(p=>`<div class="mix-summary"><b>› ${esc(p.name)}</b><span>${esc(p.dose||'—')} ${esc(p.unit||'L/ha')}</span></div>`).join('')}</div>`:''}<div class="wizard-card">${inputField('Observations','obs',wizard.obs,'Facultatif')}</div>${footer(wizard.editingId?'ENREGISTRER LES MODIFICATIONS':'ENREGISTRER LE CHANTIER','SpeedFact.saveJob()')}`}
  $('wizard').innerHTML=html}
function chooseWork(w){wizard.work=w;renderWizard()}
function syncWizard(k,v){wizard[k]=v;if(k==='client')wizard.clientId=null}
function syncBool(k,v){wizard[k]=v}
function clientInput(v){wizard.client=v;wizard.clientId=null;let sug=clientSuggestions(v),box=$('clientSug');box.innerHTML=sug.map(c=>`<button onclick="SpeedFact.pickClient(${c.id})"><b>${esc(c.name)}</b><small>${esc([c.legalName,c.city].filter(Boolean).join(' · '))}</small></button>`).join('');box.classList.toggle('hidden',!v||!sug.length)}
function pickClient(id){let c=clientById(id);if(!c)return;wizard.client=c.name;wizard.clientId=c.id;$('client').value=c.name;$('clientSug').classList.add('hidden');renderWizard()}
function nextStep(){if(wizard.step===1&&(!wizard.work||!wizard.client||!Number(wizard.ha))){alert('Indique au minimum le travail, le client et les hectares.');return}if(wizard.step===3&&isPhyto()&&!wizard.products.length){alert('Ajoute au moins un produit au mélange.');return}wizard.step++;if(!isPhyto()&&wizard.step>2)wizard.step=2;renderWizard();window.scrollTo(0,0)}
function levenshtein(a,b){a=norm(a);b=norm(b);let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]!==b[j-1]));prev=cur}return prev[b.length]}
function scoreProduct(p,q){let nq=norm(q),fields=[p.name,p.aliases,p.substances].filter(Boolean).flatMap(x=>String(x).split('|')),best=99;for(let f of fields){let nf=norm(f);if(nf===nq)return 0;if(nf.startsWith(nq))best=Math.min(best,.2);if(nf.includes(nq))best=Math.min(best,.5);if(nq.length>=4){let pref=nf.slice(0,Math.max(nq.length,Math.min(nf.length,nq.length+3)));best=Math.min(best,1+levenshtein(nq,pref)/Math.max(1,nq.length))}}return best}
function searchProducts(q){let box=$('productSug');if(!q||q.trim().length<2){box.classList.add('hidden');return}let res=(window.SPEEDFACT_PRODUCTS||[]).map(p=>[p,scoreProduct(p,q)]).filter(x=>x[1]<1.7).sort((a,b)=>a[1]-b[1]).slice(0,12);box.innerHTML=res.map(([p])=>`<button onclick="SpeedFact.addProduct('${esc(p.amm)}')"><b>${esc(p.name)}</b><small>${esc(p.substances||p.functions||'')} · AMM ${esc(p.amm)}</small></button>`).join('')||'<button type="button">Aucun résultat</button>';box.classList.remove('hidden')}
function addProduct(amm){let p=(window.SPEEDFACT_PRODUCTS||[]).find(x=>String(x.amm)===String(amm));if(!p)return;wizard.products.push({name:p.name,amm:p.amm,dose:'',unit:'L/ha',target:'',mode:'',catalog:p});$('productSug').classList.add('hidden');$('prodSearch').value='';$('mixEditor').innerHTML=renderMix()}
function renderMix(){return wizard.products.map((p,i)=>`<div class="mix-row"><div class="mix-head"><div><b>${esc(p.name)}</b><small>AMM ${esc(p.amm)}</small></div><button onclick="SpeedFact.removeProduct(${i})">Retirer</button></div><div class="field-row"><div><label>Dose / ha</label><input type="number" step="0.01" value="${esc(p.dose)}" oninput="SpeedFact.mixChange(${i},'dose',this.value)"></div><div><label>Unité</label><select onchange="SpeedFact.mixChange(${i},'unit',this.value)"><option ${p.unit==='L/ha'?'selected':''}>L/ha</option><option ${p.unit==='kg/ha'?'selected':''}>kg/ha</option><option ${p.unit==='g/ha'?'selected':''}>g/ha</option></select></div></div><label>Cible (facultatif)</label><input value="${esc(p.target||'')}" oninput="SpeedFact.mixChange(${i},'target',this.value)"></div>`).join('')||'<p class="muted">Aucun produit dans le mélange.</p>'}
function mixChange(i,k,v){if(wizard.products[i])wizard.products[i][k]=v}
function removeProduct(i){wizard.products.splice(i,1);$('mixEditor').innerHTML=renderMix()}
function ensureClientFromWizard(){let c=wizard.clientId?clientById(wizard.clientId):clientByName(wizard.client);if(!c){c=normalizeClient({id:uid(),name:wizard.client,exploitations:[]});db.clients.push(c);wizard.clientId=c.id}if(wizard.exploitation&&!c.exploitations.some(e=>norm(e.name)===norm(wizard.exploitation))){c.exploitations.push({id:uid(),name:wizard.exploitation,commune:wizard.commune||'',parcels:wizard.parcel?[wizard.parcel]:[]})}else if(wizard.exploitation&&wizard.parcel){let e=c.exploitations.find(x=>norm(x.name)===norm(wizard.exploitation));if(e&&!e.parcels.some(p=>norm(p)===norm(wizard.parcel)))e.parcels.push(wizard.parcel)}return c}
function saveJob(){let c=ensureClientFromWizard(),job={...deep(wizard),id:wizard.editingId||uid(),client:c.name,clientId:c.id,ha:Number(wizard.ha),price:Number(wizard.price||0),vat:Number(wizard.vat??db.settings.vat??20),phyto:isPhyto(),billed:wizard.editingId?(db.jobs.find(j=>j.id===wizard.editingId)?.billed||false):false};delete job.step;delete job.editingId;if(wizard.editingId){let i=db.jobs.findIndex(j=>j.id===wizard.editingId);if(i>=0)db.jobs[i]={...db.jobs[i],...job}}else db.jobs.push(job);saveDb();alert(wizard.editingId?'Chantier modifié.':'Chantier enregistré.');goHome()}
function showJobs(){show('jobs');renderJobs()}
function setJobFilter(f){jobFilter=f;document.querySelectorAll('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderJobs()}
function toggleJobFilter(){$('jobFilterBox').classList.toggle('hidden');if(!$('jobFilterBox').classList.contains('hidden'))$('jobSearch').focus()}
function renderJobs(){let q=norm($('jobSearch')?.value||''),arr=[...db.jobs].sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(jobFilter==='open')arr=arr.filter(j=>!j.billed);if(jobFilter==='billed')arr=arr.filter(j=>j.billed);if(q)arr=arr.filter(j=>norm([j.client,j.exploitation,j.work,j.parcel,j.crop].join(' ')).includes(q));let groups={};arr.forEach(j=>{let d=new Date(j.date+'T12:00:00'),k=d.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}).toUpperCase();(groups[k]??=[]).push(j)});$('jobsList').innerHTML=Object.entries(groups).map(([m,js])=>`<div class="month-title">${m}</div>${js.map(j=>jobRow(j,true)).join('')}`).join('')||'<div class="panel">Aucun chantier.</div>'}
function showBilling(){invoiceOrigin='billing';show('billing');renderBilling()}
function renderBilling(){let input=$('billingClient'),q=norm(input?.value||''),open=db.jobs.filter(j=>!j.billed),clients=[...new Set(open.map(j=>j.client))];let issuerSel=$('billingIssuer');if(issuerSel){let previous=issuerSel.value;issuerSel.innerHTML=db.issuers.map(i=>`<option value="${i.id}" ${String(i.id)===String(previous||db.settings.defaultIssuerId)?'selected':''}>${esc(i.name)}</option>`).join('')}if(input){let sug=clients.filter(c=>norm(c).includes(q)).slice(0,8),box=$('billingClientSug');box.innerHTML=sug.map(c=>`<button onclick="SpeedFact.pickBillingClient('${esc(c)}')">${esc(c)}</button>`).join('');box.classList.toggle('hidden',!q||!sug.length)}if(q)open=open.filter(j=>norm(j.client).includes(q));$('billingList').innerHTML=open.map(j=>`<label class="bill-card"><input type="checkbox" class="billcheck" value="${j.id}" checked><div><b>${esc(j.work)}</b><div>${Number(j.ha).toLocaleString('fr-FR')} ha · ${formatDate(j.date)}</div><small>${esc(j.client)}${j.exploitation?' · '+esc(j.exploitation):''}${j.parcel?' · '+esc(j.parcel):''} · TVA ${Number(j.vat||0).toLocaleString('fr-FR')}%</small></div><b>${eur(j.ha*j.price)}</b></label>`).join('')||'<div class="panel">Aucun travail non facturé.</div>'}
function pickBillingClient(c){$('billingClient').value=c;$('billingClientSug').classList.add('hidden');renderBilling()}
function snapshotIssuer(i){return deep(i||currentIssuer())}
function snapshotClient(c){return deep(c||normalizeClient({name:''}))}
function createInvoice(){let ids=[...document.querySelectorAll('.billcheck:checked')].map(x=>Number(x.value)),jobs=db.jobs.filter(j=>ids.includes(j.id));if(!jobs.length){alert('Sélectionne au moins un chantier.');return}let clientName=jobs[0].client;if(jobs.some(j=>norm(j.client)!==norm(clientName))){alert('Une facture ne peut contenir qu’un seul client. Filtre d’abord par client.');return}let c=clientById(jobs[0].clientId)||clientByName(clientName),issuer=db.issuers.find(i=>String(i.id)===String($('billingIssuer')?.value))||currentIssuer(),num=`${new Date().getFullYear()}-${String(db.invoiceSeq).padStart(4,'0')}`;currentInvoice={id:uid(),num,date:today(),ids,jobs:deep(jobs),client:clientName,clientSnapshot:snapshotClient(c),issuerId:issuer.id,issuerSnapshot:snapshotIssuer(issuer),status:'draft'};invoiceOrigin='billing';$('invoiceDocument').innerHTML=renderInvoice(currentInvoice);show('invoice')}
function totals(inv){let byVat={};inv.jobs.forEach(j=>{let ht=Number(j.ha||0)*Number(j.price||0),v=Number(j.vat||0);if(!byVat[v])byVat[v]={base:0,tax:0};byVat[v].base+=ht;byVat[v].tax+=ht*v/100});let ht=Object.values(byVat).reduce((s,x)=>s+x.base,0),tax=Object.values(byVat).reduce((s,x)=>s+x.tax,0);return {byVat,ht,tax,ttc:ht+tax}}
function addressHtml(x){return [x.legalName&&x.legalName!==x.name?x.legalName:'',x.address,[x.zip,x.city].filter(Boolean).join(' ')].filter(Boolean).map(esc).join('<br>')}
function renderInvoice(inv){let i=inv.issuerSnapshot||currentIssuer(),c=inv.clientSnapshot||clientByName(inv.client)||{},t=totals(inv),vatRows=Object.entries(t.byVat).sort((a,b)=>Number(b[0])-Number(a[0])).map(([v,x])=>`<tr><td>${Number(v).toLocaleString('fr-FR')} %</td><td>${eur(x.base)}</td><td>${eur(x.tax)}</td></tr>`).join('');return `<article class="invoice-page"><img class="invoice-watermark" src="assets/mea-logo.png" alt=""><div class="invoice-head"><div class="issuer-brand"><img src="assets/mea-logo.png" alt="Logo MEA"><div><div class="invoice-title">FACTURE</div><b>${esc(i.name||'MEA')}</b><small>${addressHtml(i)}${i.siret?`<br>SIRET : ${esc(i.siret)}`:''}${i.vatNo?`<br>TVA : ${esc(i.vatNo)}`:''}${i.approval?`<br>Agrément phyto : ${esc(i.approval)}`:''}</small></div></div><div class="invoice-meta"><b>N° ${esc(inv.num)}</b><span>${formatDate(inv.date)}</span></div></div><div class="invoice-parties"><div><small>ÉMETTEUR</small><b>${esc(i.name||'MEA')}</b><p>${addressHtml(i)}</p>${i.phone?`<p>${esc(i.phone)}</p>`:''}${i.email?`<p>${esc(i.email)}</p>`:''}</div><div><small>CLIENT</small><b>${esc(c.name||inv.client)}</b><p>${addressHtml(c)}</p>${c.siret?`<p>SIRET : ${esc(c.siret)}</p>`:''}${c.vatNo?`<p>TVA : ${esc(c.vatNo)}</p>`:''}</div></div><table class="invoice-table"><thead><tr><th>Date / exploitation</th><th>Prestation</th><th>Qté</th><th>PU HT</th><th>TVA</th><th>Total HT</th></tr></thead><tbody>${inv.jobs.map(j=>`<tr><td>${formatDate(j.date)}<br><small>${esc(j.exploitation||'')}${j.parcel?` · ${esc(j.parcel)}`:''}</small></td><td>${esc(j.work)}</td><td>${Number(j.ha).toLocaleString('fr-FR')} ha</td><td>${eur(j.price)}</td><td>${Number(j.vat||0).toLocaleString('fr-FR')} %</td><td>${eur(j.ha*j.price)}</td></tr>`).join('')}</tbody></table><div class="invoice-bottom"><div><div class="vat-box"><b>RÉCAPITULATIF TVA</b><table><thead><tr><th>Taux</th><th>Base HT</th><th>TVA</th></tr></thead><tbody>${vatRows}</tbody></table></div><div class="payment-box"><b>CONDITIONS DE RÈGLEMENT</b><p>${esc(i.paymentTerms||'')}</p>${i.iban?`<p><b>IBAN :</b> ${esc(i.iban)}${i.bic?` · <b>BIC :</b> ${esc(i.bic)}`:''}</p>`:''}${i.bank?`<p>${esc(i.bank)}</p>`:''}</div></div><div class="invoice-total"><div>Total HT <b>${eur(t.ht)}</b></div><div>Total TVA <b>${eur(t.tax)}</b></div><strong>TOTAL TTC <span>${eur(t.ttc)}</span></strong></div></div><div class="annex-note"><b>ANNEXES</b> · ${inv.jobs.length} fiche${inv.jobs.length>1?'s':''} travaux jointe${inv.jobs.length>1?'s':''} à cette facture.</div><div class="invoice-footer">Merci de votre confiance · Document généré par Speed Fact</div></article>${inv.jobs.map((j,n)=>renderAnnex(j,n+1,i)).join('')}`}
function renderAnnex(j,n,issuer){return `<article class="annex-page"><div class="annex-head"><div class="annex-logo"><img src="assets/mea-logo.png" alt="Logo"><div><b>${esc(issuer.name||'MEA')}</b><small>Fiche travaux n° ${n}</small></div></div><div><b>FICHE TRAVAUX</b><br><small>${j.phyto?'Traitement phytosanitaire':'Travaux agricoles'}</small></div></div><div class="annex-grid"><div><b>Client</b><br>${esc(j.client)}</div><div><b>Exploitation</b><br>${esc(j.exploitation||'—')}</div><div><b>Date</b><br>${formatDate(j.date)}</div><div><b>Surface</b><br>${Number(j.ha).toLocaleString('fr-FR')} ha</div><div><b>Travail</b><br>${esc(j.work)}</div><div><b>Parcelle</b><br>${esc(j.parcel||'—')}</div><div><b>Commune</b><br>${esc(j.commune||'—')}</div>${j.phyto?`<div><b>Culture</b><br>${esc(j.crop||'—')}</div><div><b>Stade BBCH</b><br>${esc(j.bbch||'—')}</div><div><b>AB</b><br>${j.organic?'Oui':'Non'}${j.conversion?' · Conversion':''}</div><div><b>RPG / localisation</b><br>${esc(j.rpg||j.location||'—')}</div>`:''}</div>${j.phyto?`<h3>Produits utilisés</h3><table class="annex-prod"><thead><tr><th>Produit</th><th>AMM</th><th>Dose / ha</th><th>Cible</th></tr></thead><tbody>${(j.products||[]).map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.amm)}</td><td>${esc(p.dose)} ${esc(p.unit)}</td><td>${esc(p.target||'')}</td></tr>`).join('')}</tbody></table>`:''}${j.obs?`<p><b>Observations :</b> ${esc(j.obs)}</p>`:''}</article>`}
function finalizeInvoice(){if(!currentInvoice)return;let existing=db.invoices.find(x=>x.id===currentInvoice.id);if(!existing){currentInvoice.status='sent';currentInvoice.sentAt=new Date().toISOString();db.invoices.push(deep(currentInvoice));currentInvoice.ids.forEach(id=>{let j=db.jobs.find(x=>x.id===id);if(j){j.billed=true;j.invoiceNo=currentInvoice.num}});db.invoiceSeq++}else{existing.status='sent';existing.sentAt=existing.sentAt||new Date().toISOString()}saveDb()}
function sendInvoice(){if(!currentInvoice)return;let c=currentInvoice.clientSnapshot||{},emails=[c.email,...(c.emails||[])].filter(Boolean).join(',');if(!emails){alert('Aucune adresse e-mail n’est enregistrée pour ce client. Ajoute-la dans sa fiche client.');return}finalizeInvoice();let subj=encodeURIComponent(`Facture ${currentInvoice.num} - ${currentInvoice.client}`),body=encodeURIComponent(`Bonjour,\n\nVeuillez trouver la facture ${currentInvoice.num} accompagnée de toutes les fiches travaux correspondantes.\n\nCordialement,\n${currentInvoice.issuerSnapshot?.name||'MEA'}`);location.href=`mailto:${encodeURIComponent(emails)}?subject=${subj}&body=${body}`;alert('La facture est enregistrée comme envoyée. Le document à transmettre est toujours la facture + toutes les fiches travaux. Utilise “PDF / Imprimer” pour créer le PDF complet puis joins-le au mail.')}
function backFromInvoice(){invoiceOrigin==='history'?showInvoiceHistory():showBilling()}
function showInvoiceHistory(){invoiceOrigin='history';show('history');renderInvoiceHistory()}
function renderInvoiceHistory(){$('invoiceHistory').innerHTML=[...db.invoices].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(inv=>{let t=totals(inv);return `<button class="history-card" onclick="SpeedFact.openHistoricInvoice(${inv.id})"><div><b>${esc(inv.num)}</b><span>${esc(inv.client)}</span><small>${formatDate(inv.date)} · ${esc(inv.issuerSnapshot?.name||'')}</small></div><strong>${eur(t.ttc)}</strong></button>`}).join('')||'<div class="panel">Aucune facture enregistrée.</div>'}
function openHistoricInvoice(id){let inv=db.invoices.find(x=>x.id===id);if(!inv)return;currentInvoice=deep(inv);invoiceOrigin='history';$('invoiceDocument').innerHTML=renderInvoice(currentInvoice);show('invoice')}
function openSettings(){show('settings');$('vat').value=db.settings.vat??20;$('catalogStatus').textContent=`${(window.SPEEDFACT_PRODUCTS||[]).length.toLocaleString('fr-FR')} produits autorisés chargés.`}
function saveSettings(){db.settings.vat=Number($('vat').value)||0;saveDb();alert('Réglages enregistrés.')}
function openIssuers(){show('issuers');editingIssuerId=null;renderIssuerList();$('issuerEditor').innerHTML=''}
function renderIssuerList(){$('issuerList').innerHTML=db.issuers.map(i=>`<div class="master-card"><button class="master-main" onclick="SpeedFact.editIssuer(${i.id})"><b>${esc(i.name)}</b><small>${esc(i.legalName||'')}${i.siret?' · SIRET '+esc(i.siret):''}</small>${String(i.id)===String(db.settings.defaultIssuerId)?'<span class="default-pill">Par défaut</span>':''}</button><button class="danger-btn" onclick="SpeedFact.deleteIssuer(${i.id})">×</button></div>`).join('')||'<div class="panel">Aucune entreprise.</div>'}
function newIssuer(){editingIssuerId='new';renderIssuerEditor(defaultIssuer())}
function editIssuer(id){let i=db.issuers.find(x=>x.id===id);if(!i)return;editingIssuerId=id;renderIssuerEditor(deep(i))}
function renderIssuerEditor(i){$('issuerEditor').innerHTML=`<div class="panel form-stack editor-panel"><h3>${editingIssuerId==='new'?'Nouvelle entreprise':'Modifier l’entreprise'}</h3><label>Nom affiché</label><input id="ie-name" value="${esc(i.name)}"><label>Raison sociale</label><input id="ie-legal" value="${esc(i.legalName)}"><label>Adresse</label><input id="ie-address" value="${esc(i.address)}"><div class="field-row"><div><label>Code postal</label><input id="ie-zip" value="${esc(i.zip)}"></div><div><label>Ville</label><input id="ie-city" value="${esc(i.city)}"></div></div><label>SIRET</label><input id="ie-siret" value="${esc(i.siret)}"><label>N° TVA</label><input id="ie-vatno" value="${esc(i.vatNo)}"><div class="field-row"><div><label>Téléphone</label><input id="ie-phone" value="${esc(i.phone)}"></div><div><label>E-mail</label><input id="ie-email" type="email" value="${esc(i.email)}"></div></div><label>N° agrément phyto</label><input id="ie-approval" value="${esc(i.approval)}"><label>IBAN</label><input id="ie-iban" value="${esc(i.iban)}"><div class="field-row"><div><label>BIC</label><input id="ie-bic" value="${esc(i.bic)}"></div><div><label>Banque</label><input id="ie-bank" value="${esc(i.bank)}"></div></div><label>Conditions de règlement</label><input id="ie-terms" value="${esc(i.paymentTerms)}"><label class="check-line"><input id="ie-default" type="checkbox" ${String(i.id)===String(db.settings.defaultIssuerId)||i.default?'checked':''}> Entreprise par défaut</label><button class="cta" onclick="SpeedFact.saveIssuer()">ENREGISTRER</button></div>`;window.scrollTo(0,document.body.scrollHeight)}
function saveIssuer(){let old=editingIssuerId==='new'?defaultIssuer():db.issuers.find(x=>x.id===editingIssuerId);if(!old)return;let i={...old,name:$('ie-name').value.trim()||'Entreprise',legalName:$('ie-legal').value.trim(),address:$('ie-address').value.trim(),zip:$('ie-zip').value.trim(),city:$('ie-city').value.trim(),siret:$('ie-siret').value.trim(),vatNo:$('ie-vatno').value.trim(),phone:$('ie-phone').value.trim(),email:$('ie-email').value.trim(),approval:$('ie-approval').value.trim(),iban:$('ie-iban').value.trim(),bic:$('ie-bic').value.trim(),bank:$('ie-bank').value.trim(),paymentTerms:$('ie-terms').value.trim()};if(editingIssuerId==='new'){i.id=uid();db.issuers.push(i)}else{let idx=db.issuers.findIndex(x=>x.id===editingIssuerId);db.issuers[idx]=i}if($('ie-default').checked||!db.settings.defaultIssuerId)db.settings.defaultIssuerId=i.id;db.issuers.forEach(x=>x.default=String(x.id)===String(db.settings.defaultIssuerId));saveDb();editingIssuerId=null;renderIssuerList();$('issuerEditor').innerHTML='';alert('Entreprise enregistrée.')}
function deleteIssuer(id){if(db.issuers.length<=1){alert('Il faut garder au moins une entreprise émettrice.');return}if(!confirm('Supprimer cette entreprise ? Les anciennes factures conserveront leur copie des coordonnées.'))return;db.issuers=db.issuers.filter(i=>i.id!==id);if(String(db.settings.defaultIssuerId)===String(id))db.settings.defaultIssuerId=db.issuers[0].id;saveDb();renderIssuerList();$('issuerEditor').innerHTML=''}
function openClients(){show('clients');editingClientId=null;renderClientList();$('clientEditor').innerHTML=''}
function renderClientList(){let q=norm($('clientMasterSearch')?.value||''),arr=db.clients.filter(c=>!q||norm([c.name,c.legalName,c.city,c.siret,c.email].join(' ')).includes(q));$('clientMasterList').innerHTML=arr.sort((a,b)=>a.name.localeCompare(b.name,'fr')).map(c=>`<div class="master-card"><button class="master-main" onclick="SpeedFact.editClient(${c.id})"><b>${esc(c.name)}</b><small>${esc([c.legalName,c.city,c.email].filter(Boolean).join(' · '))}</small><span>${c.exploitations.length} exploitation${c.exploitations.length>1?'s':''}</span></button><button class="danger-btn" onclick="SpeedFact.deleteClient(${c.id})">×</button></div>`).join('')||'<div class="panel">Aucun client.</div>'}
function newClient(){editingClientId='new';renderClientEditor(normalizeClient({id:uid(),name:'',exploitations:[]}))}
function editClient(id){let c=clientById(id);if(!c)return;editingClientId=id;renderClientEditor(deep(c))}
function renderClientEditor(c){$('clientEditor').innerHTML=`<div class="panel form-stack editor-panel"><h3>${editingClientId==='new'?'Nouveau client':'Modifier le client'}</h3><label>Nom court / client</label><input id="ce-name" value="${esc(c.name)}"><label>Raison sociale</label><input id="ce-legal" value="${esc(c.legalName)}"><label>Adresse</label><input id="ce-address" value="${esc(c.address)}"><div class="field-row"><div><label>Code postal</label><input id="ce-zip" value="${esc(c.zip)}"></div><div><label>Ville</label><input id="ce-city" value="${esc(c.city)}"></div></div><label>SIRET</label><input id="ce-siret" value="${esc(c.siret)}"><label>N° TVA</label><input id="ce-vatno" value="${esc(c.vatNo)}"><div class="field-row"><div><label>Téléphone</label><input id="ce-phone" value="${esc(c.phone)}"></div><div><label>E-mail principal</label><input id="ce-email" type="email" value="${esc(c.email)}"></div></div><label>Autres e-mails (séparés par des virgules)</label><input id="ce-emails" value="${esc((c.emails||[]).join(', '))}"><label>Exploitations</label><textarea id="ce-exploitations" rows="5" placeholder="Une exploitation par ligne. Optionnel : Nom | Commune | Parcelle 1, Parcelle 2">${esc((c.exploitations||[]).map(e=>[e.name,e.commune,(e.parcels||[]).join(', ')].filter(Boolean).join(' | ')).join('\n'))}</textarea><button class="cta" onclick="SpeedFact.saveClient()">ENREGISTRER</button></div>`;window.scrollTo(0,document.body.scrollHeight)}
function parseExploitations(s){return String(s||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{let [name='',commune='',parcels='']=line.split('|').map(x=>x.trim());return {id:uid(),name,commune,parcels:parcels?parcels.split(',').map(x=>x.trim()).filter(Boolean):[]}})}
function saveClient(){let old=editingClientId==='new'?normalizeClient({id:uid()}):clientById(editingClientId);if(!old)return;let c={...old,name:$('ce-name').value.trim(),legalName:$('ce-legal').value.trim(),address:$('ce-address').value.trim(),zip:$('ce-zip').value.trim(),city:$('ce-city').value.trim(),siret:$('ce-siret').value.trim(),vatNo:$('ce-vatno').value.trim(),phone:$('ce-phone').value.trim(),email:$('ce-email').value.trim(),emails:$('ce-emails').value.split(',').map(x=>x.trim()).filter(Boolean),exploitations:parseExploitations($('ce-exploitations').value)};if(!c.name){alert('Indique au moins le nom du client.');return}if(editingClientId==='new'){c.id=uid();db.clients.push(c)}else{let idx=db.clients.findIndex(x=>x.id===editingClientId);db.clients[idx]=c;db.jobs.filter(j=>String(j.clientId)===String(c.id)).forEach(j=>j.client=c.name)}saveDb();editingClientId=null;renderClientList();$('clientEditor').innerHTML='';alert('Fiche client enregistrée.')}
function deleteClient(id){if(db.jobs.some(j=>String(j.clientId)===String(id))){alert('Ce client est lié à des chantiers. Modifie ou supprime d’abord ces chantiers.');return}if(confirm('Supprimer définitivement cette fiche client ?')){db.clients=db.clients.filter(c=>c.id!==id);saveDb();renderClientList();$('clientEditor').innerHTML=''}}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download=`speed-fact-sauvegarde-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=migrate(JSON.parse(r.result));saveDb();alert('Sauvegarde restaurée.');openSettings()}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f)}
function voiceStep(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('La reconnaissance vocale n’est pas disponible dans ce navigateur. Tu peux tout saisir au clavier.');return}let r=new SR();r.lang='fr-FR';r.interimResults=false;r.onresult=e=>{let t=e.results[0][0].transcript;if(wizard.step===1){let m=t.match(/(\d+(?:[,.]\d+)?)\s*(?:ha|hectares?)/i);if(m)wizard.ha=m[1].replace(',','.');let w=db.works.find(x=>norm(t).includes(norm(x).slice(0,Math.min(6,norm(x).length))));if(w)wizard.work=w;let c=db.clients.find(x=>norm(t).includes(norm(x.name)));if(c){wizard.client=c.name;wizard.clientId=c.id}else if(!wizard.client)wizard.client=t}else if(wizard.step===2&&isPhyto())wizard.crop=wizard.crop||t;else if(wizard.step===3&&isPhyto()){let p=(window.SPEEDFACT_PRODUCTS||[]).map(x=>[x,scoreProduct(x,t)]).sort((a,b)=>a[1]-b[1])[0];if(p&&p[1]<1.7)wizard.products.push({name:p[0].name,amm:p[0].amm,dose:'',unit:'L/ha',target:'',mode:'',catalog:p[0]})}else wizard.obs=t;renderWizard()};r.start()}
function goHome(){show('home');renderHome()}
async function checkUpdate(manual=false){try{let r=await fetch(`version.json?ts=${Date.now()}`,{cache:'no-store'}),v=await r.json();if($('updateStatus'))$('updateStatus').textContent=`Version installée : ${VERSION} · version web : ${v.version}`;if(v.version!==VERSION)$('updateBanner').classList.remove('hidden');else if(manual)alert('Speed Fact est à jour.')}catch(e){if(manual)alert('Impossible de vérifier la mise à jour pour le moment.')}}
async function applyUpdate(){if('serviceWorker'in navigator){let reg=await navigator.serviceWorker.getRegistration();if(reg){await reg.update();if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});else if(reg.installing)reg.installing.addEventListener('statechange',()=>{if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'})})}}setTimeout(()=>location.reload(),800)}
function registerSW(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{reg.update();reg.addEventListener('updatefound',()=>{let w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)$('updateBanner').classList.remove('hidden')})})}).catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}
window.SpeedFact={startJob,editJob,deleteJob,goHome,showJobs,showBilling,showInvoiceHistory,openHistoricInvoice,backFromInvoice,openSettings,openIssuers,newIssuer,editIssuer,saveIssuer,deleteIssuer,openClients,newClient,editClient,saveClient,deleteClient,renderClientList,chooseWork,syncWizard,syncBool,clientInput,pickClient,nextStep,searchProducts,addProduct,removeProduct,mixChange,saveJob,setJobFilter,toggleJobFilter,renderJobs,renderBilling,pickBillingClient,createInvoice,sendInvoice,saveSettings,exportData,importData,voiceStep,checkUpdate,applyUpdate};
saveDb();renderHome();show('home');registerSW();checkUpdate(false);
})();
